from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel
from services.gemini_service import extract_timeline_events, simulate_scenario
from services.storage import get_document
import json

router = APIRouter()

class TimelineRequest(BaseModel):
    session_id: str

class SimulateRequest(BaseModel):
    session_id: str
    scenario: str

@router.post("/extract-timeline")
def extract_timeline(request: TimelineRequest):
    text = get_document(request.session_id)
    if not text:
        raise HTTPException(status_code=404, detail="Document not found")
    
    try:
        result_str = extract_timeline_events(text)
        data = json.loads(result_str)
        
        # Generate simple ICS content
        ics_content = "BEGIN:VCALENDAR\nVERSION:2.0\n"
        for i, event in enumerate(data.get("events", [])):
            ics_content += "BEGIN:VEVENT\n"
            ics_content += f"SUMMARY:{event.get('event_name')}\n"
            ics_content += f"DESCRIPTION:{event.get('obligation')}\n"
            ics_content += "END:VEVENT\n"
        ics_content += "END:VCALENDAR"
        
        return {
            "events": data.get("events", []),
            "ics_content": ics_content
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/simulate")
def simulate(request: SimulateRequest):
    text = get_document(request.session_id)
    if not text:
        raise HTTPException(status_code=404, detail="Document not found")
    
    try:
        result_str = simulate_scenario(text, request.scenario)
        return {"simulation": result_str}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/generate-dossier")
def generate_dossier(request: TimelineRequest):
    text = get_document(request.session_id)
    if not text:
        raise HTTPException(status_code=404, detail="Document not found")
    
    try:
        from fpdf import FPDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", size=12)
        
        pdf.set_font("Helvetica", style="B", size=16)
        pdf.cell(0, 10, text="Lawyer Prep Dossier", ln=True, align='C')
        
        pdf.set_font("Helvetica", style="I", size=10)
        pdf.multi_cell(0, 5, text="DISCLAIMER: This dossier contains illustrative analysis generated by AI. It is strictly for informational purposes and does NOT constitute professional legal advice. Laws vary by jurisdiction. Please consult a qualified attorney before taking any action.")
        pdf.ln(5)
        
        pdf.set_font("Helvetica", style="B", size=14)
        pdf.cell(0, 10, text="Overview", ln=True)
        
        pdf.set_font("Helvetica", size=12)
        pdf.multi_cell(0, 5, text="This document outlines key risks found in your recent analysis. Based on the uploaded document context, the following are the most critical points to review with legal counsel.")
        pdf.ln(5)
        
        pdf.set_font("Helvetica", style="B", size=14)
        pdf.cell(0, 10, text="Questions for your lawyer", ln=True)
        
        pdf.set_font("Helvetica", size=12)
        pdf.cell(0, 10, text="- What is the exact enforceability of the HIGH risk clauses?", ln=True)
        pdf.cell(0, 10, text="- Are the timelines standard for this jurisdiction?", ln=True)
        
        pdf_bytes = pdf.output()
        return Response(content=bytes(pdf_bytes), media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=dossier.pdf"})
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

class DiffRequest(BaseModel):
    session_id_1: str
    session_id_2: str

@router.post("/diff")
def diff_documents(request: DiffRequest):
    from services.gemini_service import compare_documents
    text1 = get_document(request.session_id_1)
    text2 = get_document(request.session_id_2)
    
    if not text1 or not text2:
        raise HTTPException(status_code=404, detail="One or both documents not found")
        
    try:
        result_str = compare_documents(text1, text2)
        data = json.loads(result_str)
        return {"changes": data.get("changes", [])}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

